Feature auth
victorweiss/elsass-web-devs pull request #37
Opened 2023-02-01 10:06 UTC by Trait2Jauge

2023-02-02 12:16 UTC, victorweiss commented
@Trait2Jauge C'est mieux ! Mais dans le _header pourquoi ne pas faire tout simplement : 
```twig
{% if app.user %}
```
😀

toujours dans le _header, pas besoin de checker if isVerified, de toute façon si c'est false il n'est pas sensé pouvoir être connecté

2023-02-03 07:27 UTC, Trait2Jauge commented
Effectivement, c'est plus simple 😅

2023-02-03 14:08 UTC, victorweiss requested changes
C'est bcp mieux ! 😃 
J'ai juste chipoté encore un petit peu mais globalement ça me semble bien propre là 👍

2023-02-03 14:08 UTC, victorweiss commented on src/Security/UserChecker.php
> +        if ($user->isBlocked('true')){
La définition de la méthode isBlocked() n'attend aucun paramètre : `public function isBlocked(): ?bool`

Pareil pour isVerified()

2023-02-03 14:08 UTC, victorweiss commented on templates/registration/confirmation_email.html.twig
> +<h1>Bonjour ! Merci de confirmer votre adresse email</h1>
On peut juste enlever le `!` et mettre genre `Bonjour Jean`
Je suis pas sûr que ça évitera d'arriver en spam, mais je crois que les serveurs mails en réception n'aiment pas voir les `!` et aiment bien que les mails soient en un personnalisés.

2023-02-03 14:51 UTC, Trait2Jauge commented on src/Controller/BaseController.php
> +<?php
Je pensais avoir tout enlevé, je ne le vois ni en local ni sur le repo

2023-02-03 14:55 UTC, victorweiss commented on src/Controller/BaseController.php
> +<?php
Oui c'est bon c'est un ancien commentaire je sais pas pourquoi il apparait ici.

2023-02-07 07:34 UTC, merged

2023-02-07 07:42 UTC, victorweiss commented
@Trait2Jauge Il restait des petits trucs (certains importants) si tu veux jeter un oeil aux derniers commits, mais sinon c'est mergé, c'est en ligne. Good job ! 👍😊